### ISSUE TITLE
Custom Checks Not Working

### ISSUE THREAD

**Issue by dseaton** [open-craft/jsinput-vectordraw#12]
@antoviaque @e-kolpakov 
So I haven't worked with custom checks in a while, but am unable to get them implemented. I tried even simply creating a new problem using api-example.

You can see my two buggy examples here via the assessment pilot course:
https://studio.edge.edx.org/container/i4x://DavidsonNext/Ann101/vertical/7ebf0c22f20c46ea9e7400531a3d6246?action=new

In both cases, the code is not utilizing the custom checks. For the first example, "g" should be larger than 'N", and the second example (api-example), "g" should equal "N".

Any thoughts? I am using the api-example from Master.

**Comment by mtyaka** [comment]
@dseaton When you want to use custom checks you need to specify them in the `custom_checks` JS setting. It's mentioned in the README (https://github.com/open-craft/jsinput-vectordraw/blob/master/README.md#cusotm_checks). Here's an example that's using custom checks: https://github.com/open-craft/jsinput-vectordraw/blob/master/Notes_and_Examples/4_EnergyLevels_multiVector/4_energyLevels.html#L28-L34

I added a custom check to `api-example` as part of the PR https://github.com/open-craft/jsinput-vectordraw/pull/13 to make it more obvious how to use custom checks and I updated the second example (based on api-example.html) at https://studio.edge.edx.org/container/i4x://DavidsonNext/Ann101/vertical/7ebf0c22f20c46ea9e7400531a3d6246?action=new so that it works now. I didn't update the first example because I didn't want to modify the `12_FDiagrams_LC3_Q2.html` file - I didn't want to break anything in case it's used in some other units.

Please let me know if you run into any other issues.

**Comment by dseaton** [comment]
@mtyaka Thank you for the quick feedback!

I have updated my example [https://github.com/open-craft/jsinput-vectordraw/tree/Daniel/Notes_and_Examples/12_FDiagram_LC3_Q2]("12_FDiagrams_LC3_Q2") and it is now working. Adding custom checks to the API example was really helpful. You can see the updated version here:
https://studio.edge.edx.org/container/i4x://DavidsonNext/Ann101/vertical/7ebf0c22f20c46ea9e7400531a3d6246?action=new

https://github.com

**Comment by antoviaque** [comment]
@dseaton Glad it was solved! Thanks @mtyaka - closing this ticket.
